version: '3'

services:
  mascota:
    build: mascota
    mem_limit: 812m
    ports:
      - "8080:8080"
    environment:
      MY_URL: jdbc:mysql://clinica_vet:3306/duenio_mascota?createDatabaseIfNotExist=true&serverTimezone=UTC
      DB_USERNAME: root
      DB_PASSWORD: admin
    restart: always
    depends_on:
      clinica_vet:
          condition: service_healthy
  clinica_vet:
    image: mysql:8.3.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: duenio_masco
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 10s
      retries: 10